### ISSUE TITLE
Removing module dependencies via configuration

### ISSUE THREAD

**Issue by arun0009** [guzart/gulp-ng-constant#12]
I want to remove dependency injection array passed in to module completely....right now I get a blank dependency array. Is there some value I can pass like in grunt deps: false to completely remove angular.module('modulename', [ ]) to be angular.module('modulename')?

**Comment by andidev** [comment]
Same problem here, are PR's accepted?

**Comment by andidev** [comment]
For those who need this right away I have implemented this in https://www.npmjs.com/package/gulp-ng-constant-fork

**Comment by guzart** [comment]
@arun0009 thank you for reporting the issue, @andidev thanks for the PR and going thru the trouble of creating a fork for those who needed the feature.
