### ISSUE TITLE
Output single quotes

### ISSUE THREAD

**Issue by ghachey** [guzart/gulp-ng-constant#17]
optionally instead of double quotes.

**Comment by ghachey** [comment]
Seems the PR in #15 would addresses this

**Comment by guzart** [comment]
If you don't mind could you say the reason you need single quotes? Is it because of the linter?

**Comment by ghachey** [comment]
Hi, yes. I configure my linter to enforce all single quotes.

**Comment by johannesjo** [comment]
Same issue here.
