### ISSUE TITLE
Please upload newest build to npm - Parsing .yml files

### ISSUE THREAD

**Issue by slnowak** [guzart/gulp-ng-constant#18]
Hi, 

I'm trying to parse config saved in .yml file. But unfortunately, I'm still getting errors like 
'SyntaxError: Unexpected token a'

Here's the code causing this:
var data = file.isNull() ? {} : JSON.parse(file.contents);  (index.js, line 47)

After a quick research, I found out that the following commit should fix it:
https://github.com/guzart/gulp-ng-constant/commit/adca6bdb830b519918175d3c3dfb34fe356a4185

So it turns out there's obsolete version on the npm. Could you please upload newest build?

**Comment by guzart** [comment]
Released version 1.0.0, please try it out, let me know if it helps.. tho... am almost sure you probably already solve this. Sorry for the long delay.

**Comment by guzart** [comment]
Feel free to reopen the issue if you have problems with YAML config.
