### ISSUE TITLE
Constants replaced instead of merged

### ISSUE THREAD

**Issue by sdornan** [guzart/gulp-ng-constant#22]
I have a gulp-ng-constant task like this:
```javascript
gulp.task('config', function() {
  var configPath = 'env.json';

  return gulp.src(configPath)
    .pipe($.ngConstant({
      name: 'app.env',
      constants: { env: { authPath: /profiles/authenticate/ } },
      wrap: 'commonjs'
    }))
    .pipe(gulp.dest(path.join(conf.paths.src, '/app')));
});
```

and an env.json file like this:
```json
{
  "env": {
    "backend": "http://0.0.0.0:8000",
  }
}
```

Given those parameters, I end up with an env.js file like this:
```javascript
module.exports = angular.module("app.env", [])

.constant("env", {
	"authPath": "/profiles/authenticate/"
})

;
```

I expected the constants in the json file to be merged rather than replaced since an extra variable isn't likely to cause problems vs. a missing variable. Agree, disagree?

**Comment by guzart** [comment]
I don't think it should be the default behaviour, but I've added a `merge` option you can set it to true for merging. Let's see how it works.
