### ISSUE TITLE
Any plans to add support for Angular 2?

### ISSUE THREAD

**Issue by adambuczynski** [guzart/gulp-ng-constant#31]
As the title says :)

**Comment by Jackson88** [comment]
that would be great!

**Comment by guzart** [comment]
@adambuczynski @Jackson88  I haven't dived into Angular 2, but I imagine there's a better way to handle configuration. Any ideas?

**Comment by adambuczynski** [comment]
@guzart I don't think this plugin is going to be necessary perse, since you can use TypeScript with Angular 2, or even just ES6 modules, and include a configuration object/array from just about anywhere. So the need for an angular module wrapper will probably disappear.

I've started working on a simple seed project for Angular 2, and so far haven't needed the plugin, but will let you know if that changes.
