### ISSUE TITLE
Version 2 released as version 1.2

### ISSUE THREAD

**Issue by briepace** [guzart/gulp-ng-constant#50]
I don't know if this is intentional or not but it broke a build process that was looking for ngConstants.js and then couldn't find it due to the new way output filenames are done.

**Comment by briepace** [comment]
This line appears to be the issue and can be found in the following commit targeted towards v2.0.0-3. It looks like the changes to remove gulp utils got moved to the 1-stable branch without removing v2 specific code.

Line number: https://github.com/guzart/gulp-ng-constant/blob/1-stable/index.js#L36

v2.0.0-3 commit: https://github.com/guzart/gulp-ng-constant/commit/ba78320110ea85fda8f7c3bc2f4c1cd36decd641#diff-168726dbe96b3ce427e7fedce31bb0bc

v1.2.0 commit: https://github.com/guzart/gulp-ng-constant/commit/910747a480d083e49065190f8b62f114e5368521#diff-168726dbe96b3ce427e7fedce31bb0bc

If you view the history of index.js on the 1-stable branch you can see that your Travis CI build failed with this commit.

**Comment by briepace** [comment]
Nevermind. Ignore. Missed the error on our end. Our end was declaring the name parameter, but since v1.1.0 was ignoring it the build process was just looking for ngConstants.js. Version 1.2.0 accepting the name parameter is what broke it, but we shouldn't have been declaring it in the first place.

**Comment by guzart** [comment]
Thank you for updating the issue! 👍
